#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "pgadmin"
name = "pgAdmin4"
description.en = "Manage PostgreSQL databases over the web"
description.fr = "Application web de gestion des bases de données PostgreSQL"

version = "8.9~ynh1"

maintainers = ["Josué Tille"]

[upstream]
license = "PostgreSQL"
website = "https://www.pgadmin.org"
admindoc = "https://www.pgadmin.org/docs"
cpe = "cpe:2.3:a:pgadmin:pgadmin"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = true
sso = true
disk = "700M"
ram.build = "300M"
ram.runtime = "200M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/pgadmin"

    [install.init_main_permission]
    type = "group"
    default = "admins"

[resources]
    [resources.sources.pgadmin_prebuilt_armv7_bookworm]
    prefetch = false
    armhf.url = "https://github.com/YunoHost-Apps/pgadmin_python_build/releases/download/v8.9/pgadmin_8.9-bookworm-bin1_armv7l.tar.gz"
    armhf.sha256 = "d62b25fc23e7353cd4f5693af9f78b1fb60a114724a1ff1adfaee306606f31b8"

    [resources.sources.pgadmin_prebuilt_armv7_bullseye]
    prefetch = false
    armhf.url = "https://github.com/YunoHost-Apps/pgadmin_python_build/releases/download/v8.9/pgadmin_8.9-bullseye-bin1_armv7l.tar.gz"
    armhf.sha256 = "4f5610b0c5ab3bc7c934dc2d3e0f25b23ed1e89e7814794fd21aec774a3dffd3"

    [resources.system_user]
    allow_email = true
    home = "/opt/yunohost/__APP__"

    [resources.install_dir]
    dir = "/opt/yunohost/__APP__"

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = [
        "python3-pip",
        "build-essential",
        "python3-dev",
        "python3-venv",
        "postgresql",
        "libpq-dev",
        "libkrb5-dev",
    ]

    [resources.database]
    type = "postgresql"
