#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "pgadmin"
name = "pgAdmin4"
description.en = "Manage PostgreSQL databases over the web"
description.fr = "Application web de gestion des bases de données PostgreSQL"

version = "8.12~ynh1"

maintainers = ["Josué Tille"]

[upstream]
license = "PostgreSQL"
website = "https://www.pgadmin.org"
admindoc = "https://www.pgadmin.org/docs"
cpe = "cpe:2.3:a:pgadmin:pgadmin"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = "all"
multi_instance = true
ldap = true
sso = true
disk = "700M"
ram.build = "300M"
ram.runtime = "200M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/pgadmin"

    [install.init_main_permission]
    type = "group"
    default = "admins"

[resources]
    [resources.sources.pgadmin_prebuilt_armv7_bookworm]
    prefetch = false
    armhf.url = "https://github.com/YunoHost-Apps/pgadmin_python_build/releases/download/v8.12/pgadmin_8.12-bookworm-bin1_armv7l.tar.gz"
    armhf.sha256 = "1aaf7b1220fe35adcdd8147a44aee865de2a681b3520d4e0eb42bb82c2b1747f"

    [resources.sources.pgadmin_prebuilt_armv7_bullseye]
    prefetch = false
    armhf.url = "https://github.com/YunoHost-Apps/pgadmin_python_build/releases/download/v8.12/pgadmin_8.12-bullseye-bin1_armv7l.tar.gz"
    armhf.sha256 = "aac84a782af91f5e9b52065511696bd4979e4d6d345577ef54516add2c814e87"

    [resources.system_user]
    allow_email = true

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = [
        "python3-pip",
        "build-essential",
        "python3-dev",
        "python3-venv",
        "postgresql",
        "libpq-dev",
        "libkrb5-dev",
    ]

    [resources.database]
    type = "postgresql"
