#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "pgadmin"
name = "pgAdmin4"
description.en = "Manage PostgreSQL databases over the web"
description.fr = "Application web de gestion des bases de données PostgreSQL"

version = "8.10~ynh1"

maintainers = ["Josué Tille"]

[upstream]
license = "PostgreSQL"
website = "https://www.pgadmin.org"
admindoc = "https://www.pgadmin.org/docs"
cpe = "cpe:2.3:a:pgadmin:pgadmin"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = true
sso = true
disk = "700M"
ram.build = "300M"
ram.runtime = "200M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/pgadmin"

    [install.init_main_permission]
    type = "group"
    default = "admins"

[resources]
    [resources.sources.pgadmin_prebuilt_armv7_bookworm]
    prefetch = false
    armhf.url = "https://github.com/YunoHost-Apps/pgadmin_python_build/releases/download/v8.10/pgadmin_8.10-bookworm-bin1_armv7l.tar.gz"
    armhf.sha256 = "a4887ee52021bbb196f93af8fb87d62767cb95ada14b09fd1810fe192f1f4d50"

    [resources.sources.pgadmin_prebuilt_armv7_bullseye]
    prefetch = false
    armhf.url = "https://github.com/YunoHost-Apps/pgadmin_python_build/releases/download/v8.10/pgadmin_8.10-bullseye-bin1_armv7l.tar.gz"
    armhf.sha256 = "db74667fd08b7bc0115da36101221119c62e27d5561ccaf8dfb68009dfd6544e"

    [resources.system_user]
    allow_email = true
    home = "/opt/yunohost/__APP__"

    [resources.install_dir]
    dir = "/opt/yunohost/__APP__"

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = [
        "python3-pip",
        "build-essential",
        "python3-dev",
        "python3-venv",
        "postgresql",
        "libpq-dev",
        "libkrb5-dev",
    ]

    [resources.database]
    type = "postgresql"
