#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "pgadmin"
name = "pgAdmin4"
description.en = "Manage PostgreSQL databases over the web"
description.fr = "Application web de gestion des bases de données PostgreSQL"

version = "9.8~ynh1"

maintainers = ["Josué Tille"]

[upstream]
license = "PostgreSQL"
website = "https://www.pgadmin.org"
admindoc = "https://www.pgadmin.org/docs"
cpe = "cpe:2.3:a:pgadmin:pgadmin"

[integration]
yunohost = ">= 12.0.0"
helpers_version = "2.1"
architectures = "all"
multi_instance = true
ldap = false
sso = true
disk = "700M"
ram.build = "300M"
ram.runtime = "200M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/pgadmin"

    [install.init_main_permission]
    type = "group"
    default = "admins"

[resources]
    [resources.sources.pgadmin_prebuilt_armv7_bookworm]
    prefetch = false
    armhf.url = "https://github.com/YunoHost-Apps/pgadmin_python_build/releases/download/v9.8/pgadmin_9.8-bookworm-bin1_armv7l.tar.gz"
    armhf.sha256 = "83035c76a3cbb630cec878c3233dc8ba188ee5fe4fbc6e25ac878426d25f9f22"

    [resources.sources.pgadmin_prebuilt_armv7_trixie]
    prefetch = false
    armhf.url = "https://github.com/YunoHost-Apps/pgadmin_python_build/releases/download/v9.8/pgadmin_9.8-trixie-bin1_armv7l.tar.gz"
    armhf.sha256 = "e97073a9a2ea836d173e597b7eb28dc6f4629d4a4702174438f7f667feaae8ac"

    [resources.system_user]
    allow_email = true

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = [
        "python3-pip",
        "build-essential",
        "python3-dev",
        "python3-venv",
        "postgresql",
        "libpq-dev",
        "libkrb5-dev",
    ]

    [resources.database]
    type = "postgresql"
