#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]


    # -------------------------------
    # Args for install from previous versions
    # -------------------------------

    args.admin = "package_checker"
    args.password = "Sup3rS3cr3t"

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.9bad4942822c461439d0823e82b29272cf08d187.name = "7.2~ynh1"
    test_upgrade_from.94b5a404c82e951f8945450ff92243f559f8a803.name = "Last packaging v1 version"
    test_upgrade_from.55a5fd67889da37d03a5d4614168db76a8817cdb.name = "Pre improvements"
    test_upgrade_from.b1cd2eff160238a6059c9806b7301edc9edd8572.name = "Before helper 2.1"
