#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]


    # -------------------------------
    # Args for install from previous versions
    # -------------------------------

    args.admin = "package_checker"
    args.password = "Sup3rS3cr3t"

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.067601ed5bb19dde70f74a1fa1f6230a30efe6b5.name = "7.2~ynh1"
    test_upgrade_from.da90e7957a1a365f3c840df02c41cd14592030db.name = "Last packaging v1 version"
    test_upgrade_from.55a5fd67889da37d03a5d4614168db76a8817cdb.name = "Pre improvements"
