#sub_path_only rewrite ^__PATH__$ __PATH__/ permanent;
location __PATH__/ {
    proxy_pass http://unix:/run/__APP__/app.socket;
    include proxy_params_with_auth;
#sub_path_only    proxy_set_header X-Script-Name __PATH__;

    client_max_body_size 200M;
}
