#!/bin/bash

# IMPORT GENERIC HELPERS
source /usr/share/yunohost/helpers

# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

# Import common cmd
source ../settings/scripts/_common.sh
source ../settings/scripts/psql.sh

# LOAD SETTINGS
final_path=$(ynh_app_setting_get $app final_path)
domain=$(ynh_app_setting_get $app domain)
db_name=$(ynh_app_setting_get $app db_name)

# BACKUP THE APP MAIN DIR
ynh_backup "$final_path"

# Backup config
ynh_backup "/etc/nginx/conf.d/$domain.d/$app.conf"
ynh_backup "/etc/uwsgi/apps-enabled/pgadmin.ini"

# Backup Data and LOG
ynh_backup "/var/lib/pgadmin"
ynh_backup "/var/log/pgadmin"
