#!/bin/bash

source experimental_helper.sh
source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# Postgresql superuser
#=================================================
ynh_script_progression "Configuring Postgresql superuser..."

ynh_psql_db_shell <<< "ALTER USER $db_user WITH SUPERUSER CREATEDB CREATEROLE REPLICATION"

ynh_script_progression 'Creating base directory...'

if [ -n "$(ls -A "$data_dir")" ]; then
    old_data_dir_path="${data_dir}_$(date '+%Y%m%d.%H%M%S')"
    ynh_print_warn "Data directory was not empty. Data was moved to $old_data_dir_path"
    mkdir -p "$old_data_dir_path"
    mv -t "$old_data_dir_path" "$data_dir"/*
fi
mkdir -p /var/log/"$app"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

install_source

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Configuring pgAdmin..."

ynh_config_add --template="config_local.py" --destination="$install_dir/venv/lib/python$python_version/site-packages/pgadmin4/config_local.py"
ynh_config_add --template=postgres-reg.ini --destination="$install_dir"/postgres-reg.ini
ynh_string_random --length=60 > "$data_dir"/master_pwd
set_permission

$install_dir/venv/bin/python3 "$install_dir/venv/lib/python$python_version/site-packages/pgadmin4/setup.py" setup-db

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd --template=pgadmin.service

yunohost service add $app --log "/var/log/$app/$app.log" --description 'PgAdmin application'

ynh_config_add_logrotate "/var/log/$app"

set_permission

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app.service" --action="restart" --wait_until="Listening at: unix:/run/$app/app.socket" --log_path=systemd

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
